"""Factores ilustrativos por giro (referencia técnica / benchmark; verificar con datos propios)."""
from __future__ import annotations

from app.empresa.schemas import GiroScian

# Factores kg RSU por unidad de producción anual declarada (interpretación coherente con cada unidad).
SCIAN_FACTORS: dict[str, GiroScian] = {
    "722511": GiroScian(
        giro_codigo="722511",
        sector="Servicios de alimentación",
        subsector="Restaurantes",
        descripcion="Servicios de preparación de alimentos (restaurantes)",
        factor_generacion_kg_por_unidad=0.8,
        unidad_produccion="comensales atendidos al año",
        composicion_tipica={
            "organico": 0.52,
            "papel": 0.08,
            "plastico": 0.22,
            "vidrio": 0.04,
            "aluminio": 0.02,
            "otros": 0.12,
        },
        fuente="SEMARNAT DBGIR 2020 [ESTIMADO]",
    ),
    "461110": GiroScian(
        giro_codigo="461110",
        sector="Comercio",
        subsector="Abarrotes",
        descripcion="Comercio al por menor de abarrotes y misceláneas",
        factor_generacion_kg_por_unidad=180.0,
        unidad_produccion="m² de piso de venta (equivalente anual m²·mes)",
        composicion_tipica={
            "organico": 0.18,
            "papel": 0.14,
            "plastico": 0.28,
            "vidrio": 0.06,
            "aluminio": 0.04,
            "otros": 0.30,
        },
        fuente="ESTIMADO benchmark sectorial (≈15 kg/m²/mes)",
    ),
    "236201": GiroScian(
        giro_codigo="236201",
        sector="Construcción",
        subsector="Edificación",
        descripcion="Construcción de inmuebles (edificación)",
        factor_generacion_kg_por_unidad=5.0,
        unidad_produccion="m² construidos al año",
        composicion_tipica={
            "organico": 0.12,
            "papel": 0.18,
            "plastico": 0.24,
            "vidrio": 0.08,
            "aluminio": 0.14,
            "otros": 0.24,
        },
        fuente="ESTIMADO benchmark sectorial",
    ),
    "611111": GiroScian(
        giro_codigo="611111",
        sector="Educación",
        subsector="Escolar",
        descripcion="Servicios educativos (nivel básico y medio)",
        factor_generacion_kg_por_unidad=60.0,
        unidad_produccion="alumnos (año lectivo ~200 días · 0,3 kg/alumno/día)",
        composicion_tipica={
            "organico": 0.25,
            "papel": 0.32,
            "plastico": 0.22,
            "vidrio": 0.04,
            "aluminio": 0.02,
            "otros": 0.15,
        },
        fuente="SEMARNAT DBGIR 2020 [ESTIMADO]",
    ),
    "621111": GiroScian(
        giro_codigo="621111",
        sector="Salud",
        subsector="Ambulatorio",
        descripcion="Servicios médicos y de consultorios",
        factor_generacion_kg_por_unidad=1.5,
        unidad_produccion="consultas al año",
        composicion_tipica={
            "organico": 0.15,
            "papel": 0.28,
            "plastico": 0.30,
            "vidrio": 0.05,
            "aluminio": 0.02,
            "otros": 0.20,
        },
        fuente="SEMARNAT DBGIR 2020 [ESTIMADO]",
    ),
    "713991": GiroScian(
        giro_codigo="713991",
        sector="Entretenimiento",
        subsector="Recreación",
        descripcion="Entretenimiento y recreación (visitantes)",
        factor_generacion_kg_por_unidad=0.5,
        unidad_produccion="visitantes al año",
        composicion_tipica={
            "organico": 0.38,
            "papel": 0.10,
            "plastico": 0.32,
            "vidrio": 0.05,
            "aluminio": 0.03,
            "otros": 0.12,
        },
        fuente="SEMARNAT DBGIR 2020 [ESTIMADO]",
    ),
    "721111": GiroScian(
        giro_codigo="721111",
        sector="Hospedaje",
        subsector="Hoteles",
        descripcion="Servicios de alojamiento temporal (hoteles)",
        factor_generacion_kg_por_unidad=1.2,
        unidad_produccion="habitación-noche al año",
        composicion_tipica={
            "organico": 0.40,
            "papel": 0.10,
            "plastico": 0.20,
            "vidrio": 0.08,
            "aluminio": 0.04,
            "otros": 0.18,
        },
        fuente="SEMARNAT DBGIR 2020 [ESTIMADO]",
    ),
    "311111": GiroScian(
        giro_codigo="311111",
        sector="Industria manufacturera",
        subsector="Alimentos",
        descripcion="Industria alimentaria (procesamiento)",
        factor_generacion_kg_por_unidad=80.0,
        unidad_produccion="toneladas de producto terminado al año",
        composicion_tipica={
            "organico": 0.45,
            "papel": 0.12,
            "plastico": 0.18,
            "vidrio": 0.06,
            "aluminio": 0.05,
            "otros": 0.14,
        },
        fuente="ESTIMADO benchmark sectorial",
    ),
    "321111": GiroScian(
        giro_codigo="321111",
        sector="Industria manufacturera",
        subsector="Madera",
        descripcion="Aserradero y industria primaria de la madera",
        factor_generacion_kg_por_unidad=60.0,
        unidad_produccion="toneladas de madera procesada al año",
        composicion_tipica={
            "organico": 0.55,
            "papel": 0.08,
            "plastico": 0.05,
            "vidrio": 0.02,
            "aluminio": 0.03,
            "otros": 0.27,
        },
        fuente="ESTIMADO benchmark sectorial",
    ),
    "331111": GiroScian(
        giro_codigo="331111",
        sector="Industria manufacturera",
        subsector="Metal",
        descripcion="Industria básica del hierro y del acero",
        factor_generacion_kg_por_unidad=10.0,
        unidad_produccion="toneladas de producto siderúrgico al año",
        composicion_tipica={
            "organico": 0.05,
            "papel": 0.08,
            "plastico": 0.12,
            "vidrio": 0.03,
            "aluminio": 0.35,
            "otros": 0.37,
        },
        fuente="ESTIMADO benchmark sectorial",
    ),
    "511111": GiroScian(
        giro_codigo="511111",
        sector="Información",
        subsector="Medios",
        descripcion="Producción de programación de radio, televisión y otros medios",
        factor_generacion_kg_por_unidad=125.0,
        unidad_produccion="empleados (≈250 días laborales · 0,5 kg/empleado/día)",
        composicion_tipica={
            "organico": 0.15,
            "papel": 0.38,
            "plastico": 0.18,
            "vidrio": 0.04,
            "aluminio": 0.03,
            "otros": 0.22,
        },
        fuente="ESTIMADO benchmark sectorial",
    ),
    "811121": GiroScian(
        giro_codigo="811121",
        sector="Servicios",
        subsector="Reparación",
        descripcion="Reparación y mantenimiento de automóviles y camiones",
        factor_generacion_kg_por_unidad=200.0,
        unidad_produccion="empleados (≈250 días · 0,8 kg/empleado/día)",
        composicion_tipica={
            "organico": 0.08,
            "papel": 0.10,
            "plastico": 0.22,
            "vidrio": 0.04,
            "aluminio": 0.18,
            "otros": 0.38,
        },
        fuente="ESTIMADO benchmark sectorial",
    ),
}

DEFAULT_MATERIAL_KEYS = ("organico", "papel", "plastico", "vidrio", "aluminio", "otros")
