import type { ClientPlatformStage } from '@/lib/platformRouting'

export type EvidenceOrigin = 'investigated' | 'calculated' | 'client_provided' | 'pending'
export type EvidenceScope = 'municipal' | 'state' | 'zm' | 'national' | 'comparable' | 'benchmark'

export interface ValidationModuleSectionSpec {
  id: string
  title: string
  description: string
  required: boolean
  requiredFields: string[]
  optionalFields?: string[]
  allowedOrigins: EvidenceOrigin[]
  allowedScopes: EvidenceScope[]
}

export interface ValidationModuleSpec {
  module_id: string
  legacy_number: string
  stage: ClientPlatformStage
  title: string
  subtitle: string
  executiveConclusion: string
  visualization: string
  completionCriterion: string
  nextModuleId: string | null
  fieldStudies: string[]
  blockedClaims: string[]
  sections: ValidationModuleSectionSpec[]
}

export const VALIDATION_MODULE_ORDER = [
  'guia_circularidad',
  'antecedentes_municipales',
  'city_baseline',
  'social_diagnostico',
  'capacidad_institucional',
  'marco_legal',
  'costo_omision',
  'escenarios_financieros',
  'riesgos_modelo',
  'expediente_cabildo',
] as const

export const PLANNING_MODULE_ORDER = [
  'roadmap_implementacion',
  'infraestructura',
  'organigrama',
  'logistica',
  'costos_programa',
  'mercado_materiales',
  'esquema_concesion',
  'arbol_financiamiento',
] as const

export const EXECUTION_MODULE_ORDER = [
  'inspeccion',
  'monitoreo_operativo',
  'doble_materialidad',
  'trazabilidad',
  'evm_dashboard',
  'risk_dashboard',
] as const

const commonScopes: EvidenceScope[] = ['municipal', 'state', 'zm', 'national', 'comparable', 'benchmark']
const traceableOrigins: EvidenceOrigin[] = ['investigated', 'calculated', 'client_provided', 'pending']

export const VALIDATION_MODULE_SPECS: Record<string, ValidationModuleSpec> = {
  guia_circularidad: {
    module_id: 'guia_circularidad',
    legacy_number: 'M00',
    stage: 'validation',
    title: 'Cómo leer este diagnóstico',
    subtitle: 'Guía de navegación · M00',
    executiveConclusion: 'El diagnóstico sólo avanza con datos investigados, calculados con fórmula o provistos por el cliente; lo demás queda como brecha visible.',
    visualization: 'Diagrama estático de flujo entre módulos M00-M15.',
    completionCriterion: 'Click humano en “He leído la guía, continuar”.',
    nextModuleId: 'antecedentes_municipales',
    fieldStudies: [],
    blockedClaims: ['Cualquier cifra municipal dentro de M00.'],
    sections: [
      {
        id: 'philosophy',
        title: 'La filosofía ALQUIMIA',
        description: 'Cero invención, cálculo trazable, evidencia jerárquica y revisión humana.',
        required: true,
        requiredFields: ['Tres categorías válidas de datos', 'Límites de uso', 'Regla de no oficialidad para cálculos'],
        allowedOrigins: ['pending'],
        allowedScopes: ['municipal'],
      },
      {
        id: 'badges',
        title: 'Sellos visibles',
        description: 'Investigado, calculado, de tu documento y pendiente.',
        required: true,
        requiredFields: ['Sello de origen', 'Alcance territorial', 'Confianza'],
        allowedOrigins: traceableOrigins,
        allowedScopes: commonScopes,
      },
    ],
  },
  antecedentes_municipales: {
    module_id: 'antecedentes_municipales',
    legacy_number: 'M00B',
    stage: 'validation',
    title: 'Antecedentes del municipio',
    subtitle: 'Contexto institucional · M00B',
    executiveConclusion: 'El módulo construye contexto institucional antes de cuantificar residuos; si falta documento, se muestra como brecha, no como narrativa inventada.',
    visualization: 'Tabla de Cabildo, línea de reformas y organigrama si hay documento.',
    completionCriterion: 'Secciones 1-5 completas; prensa/programas previos opcional.',
    nextModuleId: 'city_baseline',
    fieldStudies: [],
    blockedClaims: ['Composición política, organigrama o concesión sin fuente documental o pública.'],
    sections: [
      {
        id: 'basic_data',
        title: 'Datos básicos del municipio',
        description: 'Nombre, estado, clave INEGI, población, superficie y localidades.',
        required: true,
        requiredFields: ['Nombre', 'Estado', 'Clave INEGI', 'Población', 'Superficie', 'Localidades'],
        allowedOrigins: ['investigated', 'client_provided'],
        allowedScopes: ['municipal'],
      },
      {
        id: 'cabildo',
        title: 'Composición política del Cabildo',
        description: 'Presidencia, periodo, regidores y comisiones vinculadas a RSU.',
        required: true,
        requiredFields: ['Presidente municipal', 'Periodo', 'Regidores', 'Comisiones RSU'],
        allowedOrigins: ['investigated', 'client_provided'],
        allowedScopes: ['municipal', 'state'],
      },
      {
        id: 'legal_context',
        title: 'Marco normativo vigente',
        description: 'Reglamento, PMD y documentos institucionales base.',
        required: true,
        requiredFields: ['Reglamento vigente', 'Plan Municipal de Desarrollo'],
        optionalFields: ['Bando', 'Reglamento orgánico', 'Convenios intermunicipales'],
        allowedOrigins: ['client_provided', 'investigated'],
        allowedScopes: ['municipal', 'state'],
      },
    ],
  },
  city_baseline: {
    module_id: 'city_baseline',
    legacy_number: 'M01',
    stage: 'validation',
    title: 'Diagnóstico de residuos sólidos',
    subtitle: 'Línea base · M01',
    executiveConclusion: 'La línea base RSU puede calcularse preliminarmente, pero la composición local sólo se afirma con estudio local o documento del cliente.',
    visualization: 'Flujo 100% RSU + Sankey generación → fracciones → destino + composición.',
    completionCriterion: 'Generación, composición, recolección y disposición con datos trazables o brecha crítica visible.',
    nextModuleId: 'social_diagnostico',
    fieldStudies: ['Cuarteo NMX-AA-015', 'Estudio de rutas y tiempos', 'Datos operativos reales', 'Título/cumplimiento NOM-083'],
    blockedClaims: ['Composición municipal sin cuarteo local.', 'Generación calculada como dato oficial.'],
    sections: [
      {
        id: 'generation',
        title: 'Generación de RSU',
        description: 'Toneladas/día, kg/hab/día, variación estacional y fuente principal.',
        required: true,
        requiredFields: ['Generación total diaria', 'Generación per cápita', 'Fuente principal'],
        allowedOrigins: ['client_provided', 'calculated', 'investigated', 'pending'],
        allowedScopes: ['municipal', 'national', 'comparable', 'benchmark'],
      },
      {
        id: 'composition',
        title: 'Composición de residuos',
        description: 'Fracciones valorizables y no valorizables con suma 100%.',
        required: true,
        requiredFields: ['Orgánicos', 'Papel/cartón', 'Plásticos', 'Vidrio', 'Metales', 'No valorizables'],
        allowedOrigins: ['client_provided', 'calculated', 'pending'],
        allowedScopes: ['municipal', 'national', 'comparable', 'benchmark'],
      },
      {
        id: 'collection_disposal',
        title: 'Recolección y disposición',
        description: 'Cobertura, vehículos, rutas, frecuencia y sitio de disposición.',
        required: true,
        requiredFields: ['Cobertura', 'Vehículos', 'Rutas', 'Sitio disposición', 'NOM-083'],
        allowedOrigins: ['client_provided', 'investigated', 'pending'],
        allowedScopes: ['municipal', 'state'],
      },
    ],
  },
  social_diagnostico: {
    module_id: 'social_diagnostico',
    legacy_number: 'M02',
    stage: 'validation',
    title: 'Mapa social y privado urbano',
    subtitle: 'Actores, autoridad, ciudadanía · M02',
    executiveConclusion: 'El mapa social separa actores públicos, ciudadanía y potencial privado urbano; la percepción no se inventa si no hay encuesta o fuente.',
    visualization: 'Matriz poder-interés y mapa privado urbano por categorías.',
    completionCriterion: 'Actores institucionales y sociedad civil cubiertos; privado urbano como mapa o brecha.',
    nextModuleId: 'capacidad_institucional',
    fieldStudies: ['Encuesta/percepción ciudadana', 'Censo de pepenadores', 'Padrón privado/macrogeneradores'],
    blockedClaims: ['Aceptación ciudadana inferida.', 'Captura privada sin censo, DENUE o fuente comparable etiquetada.'],
    sections: [
      {
        id: 'institutional_actors',
        title: 'Actores institucionales',
        description: 'Cabildo, direcciones municipales y autoridades relevantes.',
        required: true,
        requiredFields: ['Cabildo', 'Direcciones municipales', 'Autoridades estatales/federales'],
        allowedOrigins: ['client_provided', 'investigated'],
        allowedScopes: ['municipal', 'state', 'national'],
      },
      {
        id: 'private_capture',
        title: 'Privado urbano',
        description: 'Fraccionamientos, vivienda vertical, escuelas, plazas, mercados, hoteles, hospitales, industria ligera y macrogeneradores.',
        required: false,
        requiredFields: ['Categorías privadas identificadas'],
        allowedOrigins: ['investigated', 'client_provided', 'calculated', 'pending'],
        allowedScopes: ['municipal', 'state', 'comparable'],
      },
    ],
  },
  capacidad_institucional: {
    module_id: 'capacidad_institucional',
    legacy_number: 'M03',
    stage: 'validation',
    title: 'Capacidad institucional',
    subtitle: 'Marco normativo y cobertura · M03',
    executiveConclusion: 'La capacidad institucional se evalúa con normas, presupuesto, personal e ingresos; sin cuenta pública o presupuesto, la lectura queda condicionada.',
    visualization: 'Pirámide normativa, capacidad operativa y barras fiscales.',
    completionCriterion: 'Marco normativo, capacidad operativa y fiscal completos o con brechas críticas visibles.',
    nextModuleId: 'marco_legal',
    fieldStudies: ['Auditoría de infraestructura', 'Presupuesto/cuenta pública', 'Manual de organización'],
    blockedClaims: ['Capacidad operativa sin presupuesto, cuenta pública u organigrama.'],
    sections: [
      {
        id: 'normative_framework',
        title: 'Marco normativo aplicable',
        description: 'LGPGIR, ley estatal, reglamento municipal, NOMs y NMXs aplicables.',
        required: true,
        requiredFields: ['LGPGIR', 'Ley estatal', 'Reglamento municipal', 'NOM-083', 'NMX-AA-015'],
        allowedOrigins: ['investigated', 'client_provided'],
        allowedScopes: ['municipal', 'state', 'national'],
      },
      {
        id: 'financial_capacity',
        title: 'Capacidad fiscal y financiera',
        description: 'Ingresos propios, participaciones, aportaciones y calificación si existe.',
        required: true,
        requiredFields: ['Ingresos propios', 'Ramo 28', 'Ramo 33', 'Cuenta pública'],
        allowedOrigins: ['client_provided', 'investigated', 'pending'],
        allowedScopes: ['municipal', 'national'],
      },
    ],
  },
  marco_legal: {
    module_id: 'marco_legal',
    legacy_number: 'M03B',
    stage: 'validation',
    title: 'Reforma reglamentaria propuesta',
    subtitle: 'Tres artículos faltantes · M03B',
    executiveConclusion: 'Sin reglamento vigente no se emite plan ni declaratoria; con reglamento, la plataforma prepara brechas y borrador sujeto a revisión jurídica humana.',
    visualization: 'Matriz reglamento vigente vs propuesta.',
    completionCriterion: 'Reglamento cargado/cotejado y mínimo tres adendos con justificación técnica.',
    nextModuleId: 'costo_omision',
    fieldStudies: ['Estudio jurídico-administrativo', 'Reglamento vigente', 'Gaceta municipal'],
    blockedClaims: ['Dictamen jurídico oficial automático.', 'Obligación reglamentaria sin artículo vigente.'],
    sections: [
      {
        id: 'proposal',
        title: 'Propuesta de reforma',
        description: 'Brechas del reglamento vigente y texto exacto propuesto.',
        required: true,
        requiredFields: ['Reglamento vigente', 'Brechas', 'Adendos propuestos'],
        allowedOrigins: ['client_provided', 'investigated', 'calculated'],
        allowedScopes: ['municipal', 'state', 'comparable'],
      },
      {
        id: 'technical_justification',
        title: 'Justificación técnica de los adendos',
        description: 'Brecha legal, precedente comparable, riesgo e implicación presupuestal.',
        required: true,
        requiredFields: ['Brecha legal', 'Precedente', 'Riesgo', 'Implicación presupuestal'],
        allowedOrigins: ['investigated', 'calculated', 'client_provided'],
        allowedScopes: ['municipal', 'state', 'comparable'],
      },
    ],
  },
  costo_omision: {
    module_id: 'costo_omision',
    legacy_number: 'M04',
    stage: 'validation',
    title: 'Costo de no actuar',
    subtitle: 'Impacto financiero acumulado · M04',
    executiveConclusion: 'El costo de no actuar puede calcularse con fuentes trazables, pero nunca se presenta como ahorro garantizado.',
    visualization: 'Árbol actuar/no actuar + costo acumulado.',
    completionCriterion: 'Costos directos, indirectos y acumulado con fórmula/fuentes o brecha.',
    nextModuleId: 'escenarios_financieros',
    fieldStudies: ['Presupuesto/cuenta pública', 'Datos de disposición', 'Factores IPCC/SHCP'],
    blockedClaims: ['Ahorro garantizado.', 'Costo ambiental sin método/fuente.'],
    sections: [
      {
        id: 'direct_costs',
        title: 'Costos directos',
        description: 'Recolección, disposición y centros de transferencia.',
        required: true,
        requiredFields: ['Costo recolección', 'Costo disposición', 'Fuente presupuestal'],
        allowedOrigins: ['client_provided', 'calculated', 'pending'],
        allowedScopes: ['municipal', 'national'],
      },
      {
        id: 'ten_year_projection',
        title: 'Acumulado a 10 años',
        description: 'Proyección con población, descuento SHCP y escenarios actuar/no actuar.',
        required: true,
        requiredFields: ['Fórmula', 'Inputs', 'Tasa descuento', 'Horizonte'],
        allowedOrigins: ['calculated'],
        allowedScopes: ['municipal', 'national', 'benchmark'],
      },
    ],
  },
  escenarios_financieros: {
    module_id: 'escenarios_financieros',
    legacy_number: 'M13',
    stage: 'validation',
    title: 'Escenarios financieros',
    subtitle: 'Captura, costos y sensibilidad · M13',
    executiveConclusion: 'El cliente ve escenarios cerrados y sus límites; TIR, VPN y Monte Carlo quedan como outputs técnicos sólo cuando hay evidencia suficiente.',
    visualization: 'Escenarios cerrados + cascada económica + sensibilidad.',
    completionCriterion: 'Tres a cinco escenarios con parámetros, fórmula y fuentes o brecha explícita.',
    nextModuleId: 'riesgos_modelo',
    fieldStudies: ['Compradores/precios verificables', 'Presupuesto/cuenta pública', 'Mix de materiales M10'],
    blockedClaims: ['TIR/VPN como promesa contractual.', 'Precio de material como oficial sin cotización.'],
    sections: [
      {
        id: 'closed_scenarios',
        title: 'Escenarios cerrados',
        description: 'Mínimo viable, conservador, base, optimizado y estrés cuando haya datos.',
        required: true,
        requiredFields: ['CAPEX', 'OPEX', 'Captura', 'Mix precios', 'Límites'],
        allowedOrigins: ['calculated', 'client_provided', 'pending'],
        allowedScopes: ['municipal', 'comparable', 'benchmark'],
      },
      {
        id: 'sensitivity',
        title: 'Sensibilidad',
        description: 'Precio, captura, merma, logística y castigo por calidad.',
        required: true,
        requiredFields: ['Parámetro clave', 'Rango', 'Fuente'],
        allowedOrigins: ['calculated'],
        allowedScopes: ['municipal', 'comparable', 'benchmark'],
      },
    ],
  },
  riesgos_modelo: {
    module_id: 'riesgos_modelo',
    legacy_number: 'M14',
    stage: 'validation',
    title: 'Riesgos del programa',
    subtitle: 'ISO 31000 · M14',
    executiveConclusion: 'Los riesgos se registran con probabilidad, impacto, responsable y mitigación; la plataforma no suaviza brechas críticas.',
    visualization: 'Matriz riesgo-impacto 5x5.',
    completionCriterion: 'Mínimo 10 riesgos con campos completos y responsable humano.',
    nextModuleId: 'expediente_cabildo',
    fieldStudies: ['Auditorías previas', 'Brechas documentales', 'ISO 31000 / PMBOK'],
    blockedClaims: ['Riesgo bajo sin evidencia.', 'Mitigación sin responsable humano.'],
    sections: [
      {
        id: 'risk_register',
        title: 'Registro de riesgos',
        description: 'Riesgos políticos, legales, financieros, operativos, ambientales y sociales.',
        required: true,
        requiredFields: ['ID', 'Categoría', 'Probabilidad', 'Impacto', 'Mitigación', 'Responsable'],
        allowedOrigins: ['calculated', 'client_provided', 'investigated'],
        allowedScopes: ['municipal', 'state', 'comparable', 'benchmark'],
      },
    ],
  },
  expediente_cabildo: {
    module_id: 'expediente_cabildo',
    legacy_number: 'M15',
    stage: 'validation',
    title: 'Borrador de expediente para Cabildo',
    subtitle: 'Documento de soporte · M15',
    executiveConclusion: 'El expediente compila sólo claims defendibles, con citas, límites y revisión humana antes de cualquier uso institucional.',
    visualization: 'Matriz evidencia por claim.',
    completionCriterion: 'M00B-M14 completos o condicionados; claims sin fuente bloqueados.',
    nextModuleId: null,
    fieldStudies: ['Todos los field studies que soportan claims previos'],
    blockedClaims: ['Claim sin ledger.', 'Cumplimiento completo sin campos obligatorios.', 'Benchmark como estudio local.'],
    sections: [
      {
        id: 'claim_matrix',
        title: 'Matriz claim-evidencia',
        description: 'Claim, fuente, método, alcance, confianza, revisión humana y puede afirmarse sí/no.',
        required: true,
        requiredFields: ['Claim', 'Fuente', 'Método', 'Alcance', 'Confianza', 'Estado humano'],
        allowedOrigins: traceableOrigins,
        allowedScopes: commonScopes,
      },
    ],
  },
}

const planningAndExecutionSections = (
  requiredFields: string[],
  description: string,
): ValidationModuleSectionSpec[] => [
  {
    id: 'operational_basis',
    title: 'Base operativa',
    description,
    required: true,
    requiredFields,
    allowedOrigins: traceableOrigins,
    allowedScopes: commonScopes,
  },
  {
    id: 'human_gate',
    title: 'Gate humano y límites',
    description: 'La plataforma organiza evidencia, escenarios y brechas; las decisiones institucionales permanecen humanas.',
    required: true,
    requiredFields: ['Responsable humano', 'Criterio de avance', 'Límites de uso', 'Claims bloqueados'],
    allowedOrigins: ['client_provided', 'investigated', 'calculated', 'pending'],
    allowedScopes: ['municipal', 'state', 'national', 'comparable'],
  },
]

export const PLANNING_MODULE_SPECS: Record<string, ValidationModuleSpec> = {
  roadmap_implementacion: {
    module_id: 'roadmap_implementacion',
    legacy_number: 'M05',
    stage: 'planning',
    title: 'Hoja de ruta de implementación',
    subtitle: 'Fases, gates y responsables · M05',
    executiveConclusion: 'La planeación traduce diagnóstico y brechas en fases ejecutables sin convertir recomendaciones en decisión política automática.',
    visualization: 'Hoja de ruta por fases con gates humanos.',
    completionCriterion: 'Fases, responsables, dependencias y gates definidos con evidencia o brecha visible.',
    nextModuleId: 'infraestructura',
    fieldStudies: ['Brechas críticas de validación', 'Responsables municipales', 'Calendario institucional'],
    blockedClaims: ['Plan aprobado sin gate humano.', 'Fecha de implementación garantizada sin responsable y presupuesto.'],
    sections: planningAndExecutionSections(['Fases', 'Responsables', 'Dependencias', 'Gate humano'], 'Secuencia de implementación condicionada por evidencia, presupuesto y capacidad institucional.'),
  },
  infraestructura: {
    module_id: 'infraestructura',
    legacy_number: 'M06',
    stage: 'planning',
    title: 'Infraestructura y capacidad física',
    subtitle: 'Centros, activos y cobertura · M06',
    executiveConclusion: 'La infraestructura se dimensiona con auditoría, rutas y capacidad documentada; si falta inventario, queda como brecha de inversión.',
    visualization: 'Mapa estructural de centros, capacidad y cobertura.',
    completionCriterion: 'Activos, capacidad, cobertura y brechas de infraestructura definidos.',
    nextModuleId: 'organigrama',
    fieldStudies: ['Auditoría de infraestructura', 'Inventario de activos', 'Centros de acopio'],
    blockedClaims: ['Capacidad instalada sin inventario.', 'Cobertura territorial sin fuente municipal.'],
    sections: planningAndExecutionSections(['Centros', 'Capacidad', 'Cobertura', 'Brechas de inversión'], 'Inventario físico y cobertura operativa necesaria para ejecutar la ruta RSU.'),
  },
  organigrama: {
    module_id: 'organigrama',
    legacy_number: 'M07',
    stage: 'planning',
    title: 'Organigrama operativo',
    subtitle: 'RACI y responsabilidad institucional · M07',
    executiveConclusion: 'La plataforma propone estructura de operación, pero responsables, firmas y aprobaciones son humanas.',
    visualization: 'Organigrama operativo y matriz RACI.',
    completionCriterion: 'Roles, responsables, suplencias y escalamiento definidos o bloqueados por documento faltante.',
    nextModuleId: 'logistica',
    fieldStudies: ['Manual de organización', 'Organigrama municipal', 'Usuarios vinculados'],
    blockedClaims: ['Responsable asignado sin validación municipal.', 'Firma automática de gates.'],
    sections: planningAndExecutionSections(['Roles', 'Responsables', 'RACI', 'Escalamiento'], 'Estructura humana de operación, revisión y escalamiento para el programa.'),
  },
  logistica: {
    module_id: 'logistica',
    legacy_number: 'M08',
    stage: 'planning',
    title: 'Logística, rutas y operación',
    subtitle: 'Rutas, frecuencia y ventanas · M08',
    executiveConclusion: 'Las rutas pueden planearse preliminarmente, pero no se declaran operación real sin estudio local o datos del cliente.',
    visualization: 'Flujo operativo de rutas, ventanas y puntos críticos.',
    completionCriterion: 'Rutas, frecuencia, recursos y brechas operativas visibles.',
    nextModuleId: 'costos_programa',
    fieldStudies: ['Estudio de rutas y tiempos', 'Datos operativos reales', 'PER'],
    blockedClaims: ['Optimización de rutas como verdad local sin estudio.', 'Cobertura real sin bitácora o fuente.'],
    sections: planningAndExecutionSections(['Rutas', 'Frecuencia', 'Vehículos', 'Puntos críticos'], 'Operación diaria esperada, con brechas si no existen datos reales de ruta.'),
  },
  costos_programa: {
    module_id: 'costos_programa',
    legacy_number: 'M09',
    stage: 'planning',
    title: 'Costos del programa',
    subtitle: 'CAPEX, OPEX y fuente presupuestal · M09',
    executiveConclusion: 'Los costos se separan por inversión, operación y contingencia; cada cifra requiere fuente o fórmula trazable.',
    visualization: 'Cascada de costos CAPEX/OPEX/contingencia.',
    completionCriterion: 'Costos con fuente, fórmula, supuestos y límites de uso.',
    nextModuleId: 'mercado_materiales',
    fieldStudies: ['Presupuesto de egresos', 'Cuenta pública', 'Cotizaciones'],
    blockedClaims: ['Costo final sin cotización.', 'Presupuesto disponible sin documento público o del cliente.'],
    sections: planningAndExecutionSections(['CAPEX', 'OPEX', 'Contingencia', 'Fuente presupuestal'], 'Modelo de costos trazable que alimenta escenarios sin prometer ahorro garantizado.'),
  },
  mercado_materiales: {
    module_id: 'mercado_materiales',
    legacy_number: 'M10',
    stage: 'planning',
    title: 'Mercado de materiales y mix de precios',
    subtitle: 'Compradores, calidad, merma y logística · M10',
    executiveConclusion: 'El mix de precios se calcula por ciudad con comprador, calidad, merma, castigo y logística; no se presenta como precio oficial.',
    visualization: 'Mix de precios ponderado por material y sensibilidad.',
    completionCriterion: 'Materiales, compradores, bandas de precio, mermas y castigos definidos o bloqueados.',
    nextModuleId: 'esquema_concesion',
    fieldStudies: ['Compradores/precios verificables', 'Centros de acopio', 'Cotización de materiales'],
    blockedClaims: ['Precio oficial sin cotización.', 'Offtake garantizado sin comprador trazable.'],
    sections: planningAndExecutionSections(['Material', 'Comprador', 'Precio ponderado', 'Merma', 'Costo logístico'], 'Modelo determinístico de precio ponderado para alimentar escenarios cerrados.'),
  },
  esquema_concesion: {
    module_id: 'esquema_concesion',
    legacy_number: 'M11',
    stage: 'planning',
    title: 'Esquema operativo o concesión',
    subtitle: 'Alternativas institucionales · M11',
    executiveConclusion: 'La plataforma compara rutas operativas, concesión o alianzas; la selección contractual es humana y requiere revisión legal.',
    visualization: 'Árbol de alternativas operativo-contractuales.',
    completionCriterion: 'Alternativas, riesgos, requisitos y documentos condicionantes visibles.',
    nextModuleId: 'arbol_financiamiento',
    fieldStudies: ['Reglamento vigente', 'Estudio jurídico-administrativo', 'Cuenta pública'],
    blockedClaims: ['Concesión recomendada automáticamente.', 'Viabilidad contractual sin revisión humana.'],
    sections: planningAndExecutionSections(['Alternativas', 'Riesgos', 'Requisitos legales', 'Condiciones'], 'Comparación de vehículos operativos sin automatizar decisión contractual.'),
  },
  arbol_financiamiento: {
    module_id: 'arbol_financiamiento',
    legacy_number: 'M12',
    stage: 'planning',
    title: 'Árbol de financiamiento',
    subtitle: 'Fuentes, restricciones y ruta financiera · M12',
    executiveConclusion: 'El financiamiento se plantea como árbol de opciones con restricciones, no como promesa de fondeo.',
    visualization: 'Árbol de financiamiento y restricciones por fuente.',
    completionCriterion: 'Fuentes, requisitos, riesgos y restricciones definidos con evidencia.',
    nextModuleId: null,
    fieldStudies: ['Presupuesto', 'Cuenta pública', 'Programas estatales/federales'],
    blockedClaims: ['Fondeo disponible sin fuente vigente.', 'Capacidad financiera sin documento presupuestal.'],
    sections: planningAndExecutionSections(['Fuente', 'Requisito', 'Restricción', 'Riesgo'], 'Rutas financieras posibles, condicionadas por presupuesto, reglas y revisión humana.'),
  },
}

export const EXECUTION_MODULE_SPECS: Record<string, ValidationModuleSpec> = {
  inspeccion: {
    module_id: 'inspeccion',
    legacy_number: 'M16',
    stage: 'execution',
    title: 'Inspección y cumplimiento operativo',
    subtitle: 'Evidencia de campo · M16',
    executiveConclusion: 'La inspección registra evidencia y hallazgos; la plataforma no sanciona ni emite actos administrativos.',
    visualization: 'Bitácora de inspección y flujo de hallazgos.',
    completionCriterion: 'Inspecciones, evidencia, responsable y estado de revisión documentados.',
    nextModuleId: 'monitoreo_operativo',
    fieldStudies: ['Bitácora de campo', 'Evidencia fotográfica', 'Reglamento vigente'],
    blockedClaims: ['Sanción automática.', 'Cumplimiento declarado sin evidencia.'],
    sections: planningAndExecutionSections(['Inspección', 'Evidencia', 'Hallazgo', 'Responsable'], 'Registro operativo de inspecciones sujeto a revisión humana y debido proceso.'),
  },
  monitoreo_operativo: {
    module_id: 'monitoreo_operativo',
    legacy_number: 'M17',
    stage: 'execution',
    title: 'Monitoreo operativo',
    subtitle: 'Deltas proyectado vs real · M17',
    executiveConclusion: 'El monitoreo compara plan vs ejecución con fuente temporal; los desvíos no recalibran opacamente el modelo.',
    visualization: 'Deltas proyectado vs real por indicador.',
    completionCriterion: 'Indicadores, periodo, fuente y delta calculado con trazabilidad.',
    nextModuleId: 'doble_materialidad',
    fieldStudies: ['Bitácoras operativas', 'Pesajes', 'Reportes mensuales'],
    blockedClaims: ['Mejora operativa sin serie temporal.', 'Dato real sin fuente y fecha.'],
    sections: planningAndExecutionSections(['Indicador', 'Periodo', 'Valor proyectado', 'Valor real', 'Delta'], 'Comparación temporal entre planeación y operación real documentada.'),
  },
  doble_materialidad: {
    module_id: 'doble_materialidad',
    legacy_number: 'M18',
    stage: 'execution',
    title: 'Doble materialidad',
    subtitle: 'Impactos, riesgos y estándares · M18',
    executiveConclusion: 'La materialidad se reporta con límites de evidencia y estándar aplicable; no sustituye auditoría externa.',
    visualization: 'Matriz impacto-riesgo y estándar asociado.',
    completionCriterion: 'Impactos, riesgos, stakeholders y estándar documentados.',
    nextModuleId: 'trazabilidad',
    fieldStudies: ['Indicadores ambientales', 'Indicadores sociales', 'Estándares aplicables'],
    blockedClaims: ['Impacto ESG sin metodología.', 'Cumplimiento estándar sin evidencia.'],
    sections: planningAndExecutionSections(['Impacto', 'Riesgo', 'Stakeholder', 'Estándar'], 'Lectura de impactos y riesgos con método, alcance y límites visibles.'),
  },
  trazabilidad: {
    module_id: 'trazabilidad',
    legacy_number: 'M19',
    stage: 'execution',
    title: 'Trazabilidad y auditoría de claims',
    subtitle: 'Ledger vivo de evidencia · M19',
    executiveConclusion: 'Cada claim operativo conserva fuente, método, alcance, confianza y estado humano antes de publicarse.',
    visualization: 'Ledger de claims y evidencia asociada.',
    completionCriterion: 'Claims, fuentes, métodos, estados humanos y límites completos.',
    nextModuleId: 'evm_dashboard',
    fieldStudies: ['Claim ledger', 'Bibliografía', 'Documentos cargados'],
    blockedClaims: ['Claim sin ledger.', 'Fuente comparable presentada como estudio local.'],
    sections: planningAndExecutionSections(['Claim', 'Fuente', 'Método', 'Alcance', 'Estado humano'], 'Auditoría viva de claims para ejecución y reportes.'),
  },
  evm_dashboard: {
    module_id: 'evm_dashboard',
    legacy_number: 'M20',
    stage: 'execution',
    title: 'EVM y avance presupuestal',
    subtitle: 'Valor ganado y desviaciones · M20',
    executiveConclusion: 'El seguimiento EVM muestra avance y desviaciones con datos reales; no declara éxito sin revisión institucional.',
    visualization: 'Curva de avance, costo y valor ganado.',
    completionCriterion: 'Presupuesto, avance, periodo, variación y responsable definidos.',
    nextModuleId: 'risk_dashboard',
    fieldStudies: ['Presupuesto aprobado', 'Avance físico', 'Avance financiero'],
    blockedClaims: ['Ahorro realizado sin cuenta pública.', 'Avance físico sin evidencia.'],
    sections: planningAndExecutionSections(['Presupuesto', 'Avance físico', 'Avance financiero', 'Variación'], 'Seguimiento de valor ganado y desviaciones con evidencia temporal.'),
  },
  risk_dashboard: {
    module_id: 'risk_dashboard',
    legacy_number: 'M21',
    stage: 'execution',
    title: 'Riesgos vivos y gobernanza',
    subtitle: 'Gates, alertas y revisión humana · M21',
    executiveConclusion: 'La plataforma monitorea riesgos vivos y alertas; gates y decisiones de gobierno se cierran por personas.',
    visualization: 'Matriz de riesgos vivos y gates humanos.',
    completionCriterion: 'Riesgos, alertas, gates, dueño y estado de revisión visibles.',
    nextModuleId: null,
    fieldStudies: ['Bitácora de riesgos', 'Auditoría trimestral', 'Actas de revisión'],
    blockedClaims: ['Gate cerrado automáticamente.', 'Riesgo resuelto sin responsable humano.'],
    sections: planningAndExecutionSections(['Riesgo', 'Alerta', 'Gate', 'Dueño', 'Estado'], 'Gobernanza continua de ejecución sin automatizar decisiones políticas.'),
  },
}

export const OPERATIONAL_MODULE_SPECS: Record<string, ValidationModuleSpec> = {
  ...VALIDATION_MODULE_SPECS,
  ...PLANNING_MODULE_SPECS,
  ...EXECUTION_MODULE_SPECS,
}

export function validationModuleSpecFor(moduleId: string | null | undefined): ValidationModuleSpec | null {
  if (!moduleId) return null
  return OPERATIONAL_MODULE_SPECS[moduleId] ?? null
}

export function modulesForStage(stage: ClientPlatformStage): string[] {
  if (stage === 'validation') return [...VALIDATION_MODULE_ORDER]
  if (stage === 'planning') return [...PLANNING_MODULE_ORDER]
  return [...EXECUTION_MODULE_ORDER]
}
